export default {
  SEND_VERIFICATIONCODE_VIA_SMS: 'SEND_VERIFICATIONCODE_VIA_SMS',
  SEND_VERIFICATIONCODE_VIA_MESSANGER: 'SEND_VERIFICATIONCODE_VIA_MESSANGER',
  INIT_VERIFICATION_CODE: 'INIT_VERIFICATION_CODE',
  INIT_VERIFICATION_CODE_PROCESS: 'INIT_VERIFICATION_CODE_PROCESS'
}
