export default {
  SET_LOADING_APP: 'SET_LOADING_APP',
  INIT_TEMPLATE: 'INIT_TEMPLATE',
  TEMPLATE_CODE_SET: 'TEMPLATE_CODE_SET',
  SET_TYPE_BROWSER: 'SET_TYPE_BROWSER',
  SET_APP_CODE: 'SET_APP_CODE',
  SET_BTN_VISIBLE: 'SET_BTN_VISIBLE',
  SET_BOTTOM_OFFSET: 'SET_BOTTOM_OFFSET',
  SET_OPACITY: 'SET_OPACITY'
}
